### PR TITLE
Batch Update Users in Workspace

### LINKED ISSUE #594: Collaborator page should have a "Save" dialog to limit updates
Today adding a lead collaborator requires two changes:
1. Adding a new collaborator to the database - this triggers a pipeline run
2. Updating the role of a collaborator, this also triggers a second pipeline run

thinking if we should have a "Save" button that updates at the same time both addition of user and role... either that or add a role dialog box in the add input

### PR DESCRIPTION
**Pull request by nicksalt**
- Adds a public method to `ProjectUserManagementService` to create a batch of updates that allows multiple user updates while only triggering the pipeline once.
- Full test coverage for the new method in service tests
- Updates to the user table and invite user modal to keep track of changes and only call `ProjectUserManagementService`  when save is complete.

image
No Updates to users (no save button)

image
User Added (save button show)

image
Save clicked 

Closes #594

### CODE REVIEW

**Comment by ErikApption** [comment]
@nicksalt quickly went through changes don't see any updates in the french loc - could you check the French?

**Comment by ErikApption** [comment]
also do we have a warning if the user is going to navigate away without saving

**Comment by nicksalt** [comment]
> @nicksalt quickly went through changes don't see any updates in the french loc - could you check the French?

fixed in https://github.com/ssc-sp/datahub-portal/pull/605/commits/04b541d1a2e2c05d4fc6003b8aec0f9cd17e9f61

**Review by ErikApption — APPROVED** [review]

**Comment by ErikApption** [comment]
@nicksalt  I did not see in the changes a warning for the user if they navigate away without saving - that can be added later. Anyway @yjmrobert should merge this one

**Comment by nicksalt** [comment]
> @nicksalt I did not see in the changes a warning for the user if they navigate away without saving - that can be added later. Anyway @yjmrobert should merge this one

@ErikApption and @yjmrobert  Wonder if we should use a [library like this one](https://github.com/peterblazejewicz/blazor-beforeunload) to hook into the browser. Then we can warn the user if the close the browser or tab too.

**Review by yjmrobert — CHANGES_REQUESTED** [review]
Could we move the user enrollment (inviting) to the batch as well?

I'm wondering if it might make sense to have a `ProjectMemberChange` command-like object that tracks the change between states for a project member.

Something with `Remove`, `ChangeRole`, `Invite`, `Add` state changes and an `OldState` and `NewState`.

Could "preview" it to the UI to demo the end result and then clicking Save Changes would apply them and clicking "Cancel" would simply send them to the garbage collector. 

> Side note; could we make the save changes button smaller?


Thinking we keep track of the ones that are applied in a table for auditing.

FWIW I think this needs some clearer directions and discussions around multiple points

**Comment by yjmrobert** [comment]
@nicksalt I've created #628 for the command pattern bit, you can close this issue here once the invitation is part of the batch process!

**Review by yjmrobert — APPROVED** [review]

**Pull request merged**
