### PR TITLE
Adding redeploy button and information

### PR DESCRIPTION
**Pull request by davidreneuw**
## Description

Adding a redeploy button for whenever changes are made to docker-compose. The "Redeploy" button is only available once a webapp has been succesfully configured before.

## How Has This Been Tested?

Manually tested

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Unit test (new or update to tests)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update (change that would cause documentation to be updated)
- [ ] Configuration change (change that would affect the configuration of the application)

image

## Checklist:

- [ ] PR is submitted to the correct branch `develop`.
- [ ] Code follows the code style of this project.
- [ ] Changes are covered by Specflow tests and all new or existing tests are passing.
- [ ] Any new or updated translatable strings have been added to the localization files.
- [ ] Necessary and relevant documentation has been created or updated.
- [ ] There are either no changes to the application's configuration or the necessary changes in the infrastructure repository are included in a separate PR.

### CODE REVIEW

**Review by Sean-Stilwell — APPROVED** [review]
LGTM! One small suggestion is to use MudProgressCircular after button is clicked until the message pops up. This shows the user something happened until the message appears, like with the Restart button.

image

**Comment by ErikApption** [comment]
Do we have Redeploy = Redéployer in localization?

**Comment by davidreneuw** [comment]
> Do we have Redeploy = Redéployer in localization?

@ErikApption There will be, I just waited to do localization since there's additional text that I wanted to be reviewed (the stuff in the blue alert in the screenshot above)

**Review by Sean-Stilwell — APPROVED** [review]
LGTM!

**Pull request merged**
