### PR TITLE
✨ Web application feature

### PR DESCRIPTION
**Pull request by davidreneuw**
## Description

Git access tokens are now stored and retrieved from AKV
Git access tokens are hidden in configuration dialog
Added specflow features for new pages and components
Added and fixed unit tests for the new service and function
Added translations

## How Has This Been Tested?

The WorkspaceWebAppManagement service has been tested with unit tests that start/stop/restart/gets the state of a real test web app hosted on dev.
The ConfigureWorkspaceAppService function has been tested with unit tests that send fake configuration requests to a replica ADO pipeline. These fake configurations tests incorrect parameters and incorrect pipeline urls.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Unit test (new or update to tests)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update (change that would cause documentation to be updated)
- [ ] Configuration change (change that would affect the configuration of the application)

startstop
configuration
envvar

## Checklist:

- [x] PR is submitted to the correct branch `develop`.
- [x] Code follows the code style of this project.
- [x] Changes are covered by Specflow tests and all new or existing tests are passing.
- [x] Any new or updated translatable strings have been added to the localization files.
- [ ] Necessary and relevant documentation has been created or updated.
- [x] There are either no changes to the application's configuration or the necessary changes in the infrastructure repository are included in a separate PR.

### CODE REVIEW

**Review by yjmrobert — APPROVED** [review]

**Comment by ErikApption** [comment]
@davidreneuw noticed that it says "Do not reuse exciting token" - I've never been able to get an exciting token. All my tokens have always been extremely boring, any guidelines for an exciting one?

**Comment by yjmrobert** [comment]
@davidreneuw  can you merge `develop` into here so it picks up on the fix for the unit tests please?

**Comment by davidreneuw** [comment]
> @davidreneuw noticed that it says "Do not reuse exciting token" - I've never been able to get an exciting token. All my tokens have always been extremely boring, any guidelines for an exciting one?

@ErikApption the trick is to push your token to github, it can get very exciting then

**Comment by davidreneuw** [comment]
> @davidreneuw can you merge `develop` into here so it picks up on the fix for the unit tests please?

@yjmrobert Hey I merged `develop` into `dr/web-app-configuration` (here) locally but that brought no change. I see you also did that earlier. I also double checked that the tests are fine on this branch. Did you mean for me to merge this branch into `develop`?

**Comment by yjmrobert** [comment]
> @yjmrobert Hey I merged `develop` into `dr/web-app-configuration` (here) locally but that brought no change. I see you also did that earlier. I also double checked that the tests are fine on this branch. Did you mean for me to merge this branch into `develop`? 

Hmm no, just trying to figure out why it's failing the unit tests

**Comment by davidreneuw** [comment]
> > @yjmrobert Hey I merged `develop` into `dr/web-app-configuration` (here) locally but that brought no change. I see you also did that earlier. I also double checked that the tests are fine on this branch. Did you mean for me to merge this branch into `develop`?
> 
> Hmm no, just trying to figure out why it's failing the unit tests

Argh, super sorry about that, Im not sure what is wrong and Im fairly scared to hit the green triangle while outside of Canada. Ill have a look as soon as possible

**Comment by davidreneuw** [comment]
image

Unit tests related to this PR should be passing on anyone's machine given they are using up to date local configurations (new version available in ADO)
Please let me know if there are still issues!

**Comment by yjmrobert** [comment]
> Please let me know if there are still issues!

It's not passing the style cop rules now 😅

Take a peek at the ADO details on `ssc-sp.datahub-portal` pipeline

**Pull request merged**
