### PR TITLE
Normalized LR (CRLF) in .gitattributes and normalized existing files

### PR DESCRIPTION
**Pull request by ErikApption**
This aims to leverage git autocrlf feature that normalizes cr lf lines. Line returns could impact functionality of .razor files. The server runs on linux and pipelines are executed on linux - the repo shouldn't have any CRLF lines.

### CODE REVIEW

**Review by KingBain — CHANGES_REQUESTED** [review]
Not wanting to merge this as I think its stacking changes one top of other changes

**Comment by ErikApption** [comment]
> Not wanting to merge this as I think its stacking changes one top of other changes

Found one good example with blazor https://github.com/telerik/kendo-ui-core/blob/master/.gitattributes if we want to be specific with file types, most of them should be LF

**Comment by ErikApption** [comment]
I will close this one once we figure out the python deployment in prod

**Comment by KingBain** [comment]
Close now and we can reopen later

**Pull request closed without merging**
