### PR TITLE
Fix code scanning alert no. 14: Log entries created from user input

### PR DESCRIPTION
**Pull request by KingBain**
Fixes [https://github.com/ssc-sp/datahub-portal/security/code-scanning/14](https://github.com/ssc-sp/datahub-portal/security/code-scanning/14)

To fix the problem, we need to sanitize the `fileId` before logging it. Since the log entries are plain text, we should remove any newline characters from the `fileId` to prevent log forging. This can be done using the `String.Replace` method to replace newline characters with an empty string.

_Suggested fixes powered by Copilot Autofix. Review carefully before merging._

### CODE REVIEW

**Review by ErikApption — CHANGES_REQUESTED** [review]
this doesn't make sense - fileId is a guid. It cannot contain newlines

**Comment by KingBain** [comment]
> this doesn't make sense - fileId is a guid. It cannot contain newlines

check the teams chat

**Comment by ErikApption** [comment]
@gcalexk  can you double check? I made sure there were no references to these old open data components but can you confirm this will not impact your new flow?

**Comment by akhavich** [comment]
Looks good to me, all these items are from the old approval process and the updated one doesn't touch them.

**Review by ErikApption — APPROVED** [review]

**Pull request merged**
