### PR TITLE
:sparkles: default resources to user guide

### PR DESCRIPTION
**Pull request by ErikApption**
:sparkles: reworked hiearchy to represent sidebar
:sparkles: added support for free API key with DeepL

### CODE REVIEW

**Review by iroelperez — APPROVED** [review]

**Comment by iroelperez** [comment]
I approved the PR, just check why the build is failing.

**Comment by yjmrobert** [comment]
```
CSC : error CS2001: Source file '/home/vsts/work/1/s/Shared/src/Datahub.Shared/annotations/AnnotationTools.cs' could not be found. [/home/vsts/work/1/s/Portal/src/Datahub.Core/Datahub.Core.csproj]
CSC : error CS2001: Source file '/home/vsts/work/1/s/Shared/src/Datahub.Shared/annotations/StringValue.cs' could not be found. [/home/vsts/work/1/s/Portal/src/Datahub.Core/Datahub.Core.csproj]
```

**Comment by yjmrobert** [comment]
image

It's the casing in the shproj, it ran on a Linux agent and couldn't find the `annotations` vs `Annotations`

**Comment by yjmrobert** [comment]
I'm about to make a PR so I'll pull in the changes and fix it

cc @ErikApption @iroelperez

**Pull request merged**
