### PR TITLE
Resource Delete Feature

### PR DESCRIPTION
**Pull request by yjmrobert**
# Pull Request

> [!IMPORTANT]
> Merge #1290 before this one to help reduce the "noise" in the git diffing

## Description

This PR adds the resource deletion feature to the solution. It expands on the work done by @shudsky in #1290.

The gist of the flow is that when you want to delete a resource you update the `Status` of the `Project_Resource2` of the corresponding resource to one of `TerraformStatus` options. In this case `DeleteRequested`. 

The workspace definition then contains the new status on the template and sending it through the resource messaging service onto the service bus will cause it to be processed by the Resource Provisioner.

The resource provisioner will delete the template files in the search pattern `<template-name>.*` inside the workspace's terraform folder and replace it with a single output variable in the following format

`<template-name>.tf`
```hcl
output "<template-status-name>" {
  value = "deleted"
}
```

image

This in turn will cause ADO to run the terraform update, delete the resource, and then output that the resource has been deleted onto the service bus.

The Terraform Output Handler will pick this up and process it accordingly. Which in the delete case is simply updating the `Status` and the `UpdatedAt` values in the database.

Once the database has been updated, loading the toolbox page in the workspace will show the following UX

image

Further work can be done with regards to redeploying a resource but may involve purging any lingering data in Azure's "recycle bin", particularly around keys and key names.

## Related Issues

It also lays the foundation for additional UX feedback around provisioning for AB#6717

## Changes

- Refactored toolbox button logic into `ToolboxButton` component
- Handled delete request in `ProcessRequest` method on Portal
- Added template deletion to Resource Provisioner
- Added terraform status handling to TF Output Handler

## Testing

- Added gherkin tests for deltas
- Manually ran creation and deletion process to validate

## Checklist

- [x] Code follows dotnet coding standards
- [x] Tests added/updated to cover changes

### CODE REVIEW

**Review by Sean-Stilwell — DISMISSED** [review]
Missing i18n for the new features.

Otherwise, LGTM!

**Review by davidreneuw — COMMENTED** [review]
This looks great and I like that we're taking full advantage of the existing ResourceRunRequest, I also had a look at the terraform logs on your DT1 workspace deletion requests and it looks great. Im just going to add a code suggestion to remove deleted resources from the workspace sidebar

**Comment by yjmrobert** [comment]
> This looks great and I like that we're taking full advantage of the existing ResourceRunRequest, I also had a look at the terraform logs on your DT1 workspace deletion requests and it looks great. Im just going to add a code suggestion to remove deleted resources from the workspace sidebar

Good point! I completely forgot about that. Would just need to check it against the status

**Comment by davidreneuw** [comment]
Apparently you cannot add code suggestions that are far outside of the diff so I just made the change and commited it, hope thats alright

**Review by Sean-Stilwell — DISMISSED** [review]
LGTM! Requires the other PR to be merged first

**Review by ErikApption — APPROVED** [review]

**Pull request merged**
