### PR TITLE
Project Resource Whitelist

### PR DESCRIPTION
**Pull request by nicksalt**
Still WIP

### CODE REVIEW

**Comment by yjmrobert** [comment]
hey @nicksalt! is this still a draft?

**Comment by nicksalt** [comment]
@yjmrobert Yes... need to add a migration then it should be good.

**Comment by ErikApption** [comment]
@nicksalt beside the conflicts, can this one be merged?

**Comment by nicksalt** [comment]
Closing this PR to open a new one off of a different branch.

**Pull request closed without merging**
