### PR TITLE
Vb/python cert

### PR DESCRIPTION
**Pull request by vb-ssc**
## Description
- switch to http client instead of Azure Service Bus so that we can use custom certificate

## How Has This Been Tested?
manually

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Unit test (new or update to tests)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update (change that would cause documentation to be updated)
- [ ] Configuration change (change that would affect the configuration of the application)

## Checklist:

- [x] PR is submitted to the correct branch `develop`.
- [x] Code follows the code style of this project.
- [ ] Changes are covered by Specflow tests and all new or existing tests are passing.
- [ ] Any new or updated translatable strings have been added to the localization files.
- [ ] Necessary and relevant documentation has been created or updated.
- [x] There are either no changes to the application's configuration or the necessary changes in the infrastructure repository are included in a separate PR.

### CODE REVIEW

**Comment by simon-wang-gc** [comment]
It is REQUESTS_CA_BUNDLE not REQUEST_CA_BUNDLE

**Comment by vb-ssc** [comment]
"The requests library, which is used internally by many SDKs including databricks.sdk, will automatically use custom certificate for SSL verification using the `os.environ['REQUESTS_CA_BUNDLE']` environment variable"

**Comment by yjmrobert** [comment]
@simon-wang-gc @vb-ssc 

What is the status of this PR? Can we close it or is there still some work that needs to be merged with `develop` ?

**Comment by vb-ssc** [comment]
I guess we can kill this PR. Change did not help with the issue, and Alex was working on it since

**Pull request closed without merging**
