### PR TITLE
Remove old Integration CI/CD github Action

### PR DESCRIPTION
**Pull request by KingBain**
Noticed the action has been running and failing for a while. 

_Do a PR on your "first day"_ 

## Description
the integration branch no longer exists 

## How Has This Been Tested?
confirmed deleting the file removes the action 

## Types of changes

- [ x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Unit test (new or update to tests)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update (change that would cause documentation to be updated)
- [ ] Configuration change (change that would affect the configuration of the application)

image

## Checklist:

- [x ] PR is submitted to the correct branch `develop`.
- [ ] Code follows the code style of this project.
- [ ] Changes are covered by Specflow tests and all new or existing tests are passing.
- [ ] Any new or updated translatable strings have been added to the localization files.
- [ ] Necessary and relevant documentation has been created or updated.
- [ ] There are either no changes to the application's configuration or the necessary changes in the infrastructure repository are included in a separate PR.

For your review.

### CODE REVIEW

**Comment by yjmrobert** [comment]
But how will I know it's Monday morning now?

**Review by yjmrobert — APPROVED** [review]
Thanks 🙂

**Comment by yjmrobert** [comment]
Not sure why this is failing... bizarre - any ideas @KingBain ?

**Comment by KingBain** [comment]
> Not sure why this is failing... bizarre - any ideas @KingBain ?

I don't have access to the ado pipeline :(

**Comment by KingBain** [comment]
so I have access now. 

I have a couple thoughts, I think this is failing because of how I did the change. 

My PR is coming from my own fork of the code, the agent will be trying to push changes into my kingbain fork of datahub-portal which it shouldnt have access to. 

in these commands: https://github.com/ssc-sp/datahub-portal/blob/4e66860dc1d3fef6b3302e56bf666491985c729c/pipelines/ado-dsd-fsdh-dev-ci-linux.yml#L249C13-L249C26

```
        git tag "$versionNumber" --force
        git push origin "$versionNumber" --force"
```

I think this is the main issue, but at the same time. I also hadnt grants ADO access to my github oauth token, so it muddies the issue a bit for me. Access at two different levels :D

My other thoughts. 

My change was related to an infrastructure change not related to the build of the application. There is probably some value in setting up ignore folders in the pipeline so the trigger isnt running on every and all changes 

   paths:
    exclude:
      - .github/**
  batch: True

or if this trigger is just for portal builds, targetting just the "Portal" folder ?

**Comment by KingBain** [comment]
nuking this, will need to redo it as a local branch rather then a fork

**Pull request closed without merging**
