### PR TITLE
Adding the Project Costing model to track daily stats

### PR DESCRIPTION
**Pull request by iroelperez**
Changes:
- Updated the Project_Costs table to keep day cost per service.
- Including the workspace acronyms in the subject of consumption percent notifications
- Bcc FSDH team on consumption percent notifications

### CODE REVIEW

**Comment by yjmrobert** [comment]
Is this still a draft?

**Comment by iroelperez** [comment]
Not anymore, added 3 reviewers.

**Review by yjmrobert — APPROVED** [review]
I notice a lot of similar code from the other PR - were those the commits you cherry picked?

**Comment by iroelperez** [comment]
> 

Yes, that's why.

**Pull request merged**
